### ISSUE TITLE
Brak obsługi punktów i drużyn

### ISSUE THREAD

**Issue by drzazga888** [drzazga888/Fight-in-Square#15]

**Comment by lukasz22** [comment]
O co chodzi?

**Comment by drzazga888** [comment]
niech to zostanie moją słodką tajemnicą...

**Comment by drzazga888** [comment]
nie ważne że cię przydzieliłem ;). Z Kamilem nigdy nie wiesz co gdzie jak

**Comment by drzazga888** [comment]
Zamykam - jednak wszystko jest ok.
