### ISSUE TITLE
Czołgi nachodzą na siebie

### ISSUE THREAD

**Issue by drzazga888** [drzazga888/Fight-in-Square#16]
Jeśli przy dołączeniu nowego gracza albo przy respawnie jest losowana pozycja, to zdarza się, że czolg zostanie wylosowany na już istniejącym czołgu. Normalnie czolgi nie najeźdźają na siebie, wi<ec tamto sprawdzanie jest dobre. Trzeba tak samo skuteczne sprawdzanie zrobić przy losowaniu położenia.

**Comment by lukasz22** [comment]
Jest lepiej
